#set_property PACKAGE_PIN T2 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property PACKAGE_PIN C5 [get_ports {leds[0]}]
#set_property PACKAGE_PIN C3 [get_ports {leds[1]}]
#set_property PACKAGE_PIN B2 [get_ports {leds[2]}]
#set_property PACKAGE_PIN B1 [get_ports {leds[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {leds[*]}]
set_property PACKAGE_PIN V5 [get_ports {refclk[1]}]
set_property PACKAGE_PIN AB3 [get_ports {tx[1]}]
set_property PACKAGE_PIN Y2 [get_ports {tx[3]}]
set_property PACKAGE_PIN AB19 [get_ports aux_n]
set_property IOSTANDARD BLVDS_25 [get_ports aux_p]
set_property IOSTANDARD BLVDS_25 [get_ports aux_n]
set_property PACKAGE_PIN M2 [get_ports debug]
set_property IOSTANDARD LVCMOS33 [get_ports debug]
#set_property PACKAGE_PIN P3 [get_ports debug2]
#set_property IOSTANDARD LVCMOS33 [get_ports debug2]

create_clock -name FCLK -period 10.000 [get_pins {PS7_0/FCLKCLK[0]}]
create_clock -name USRCLK -period 12.500 [get_nets usrclk]
set_false_path -from [get_clocks FCLK] -to [get_clocks USRCLK]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

